name: diary_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans_10pt-Regular.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400

    - family: Outfit
      fonts:
        - asset: fonts/Outfit-Regular.ttf
          weight: 400

    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400



